PracProject/Controllers/LoginRegisterController.cs
using PracProject.Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PracProject.Controllers
{
    public class LoginRegisterController : Controller
    {
        HttpClient ApiCon = new HttpClient();

        public ActionResult SignUp()
        {
            try
            {
                return View();

            }catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]
        public ActionResult SignUp(SignUpModel SignUpData)
        {
            try
            {
                ApiCon.BaseAddress = new Uri("http://localhost:53084/api/SignUpApi");
                var Response = ApiCon.PostAsJsonAsync("SignUpApi", SignUpData);
                Response.Wait();
                var Test = Response.Result;
                if (Test.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Sorry We Cant Add Data";
                    return View("SignUp");
                }
            }
            catch (Exception E)
            {
                throw E;
            }
        }



        public ActionResult Login()
        {
            try
            {
                return View();
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]

        public ActionResult LoginCheck(LoginModel Logdata)
        {
            try
            {
                ApiCon.BaseAddress = new Uri("http://localhost:53084/api/LoginApi");
                var Response = ApiCon.PostAsJsonAsync("LoginApi" , Logdata);
                Response.Wait();
                var Test = Response.Result;
                if (Test.IsSuccessStatusCode)
                {
                    Session["user"] = Logdata.Email;
                    return RedirectToAction("AddStudent", "Student");
                }
                else
                {
                    ViewBag.ErrorMsg = "Invalid Credentials";
                    return View("Login");
                }
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        public ActionResult logout() {

            Session.Abandon();
            return RedirectToAction("Login");
        }
    }
}

PracProject/Controllers/StudentController.cs
using PracProject.Model.Model;
using PracProject.Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using PracProject.Model.Context;
using PracProject.Filter;

namespace PracProject.Controllers
{
    [CustomFilter]
    public class StudentController : Controller
    {
        IStudent StudentObj;

        public StudentController (IStudent Obj)
        {
            StudentObj = Obj;
        }

        public ActionResult AddStudent()
        {
            try
            {

            return View();
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]

        public ActionResult AddStudent(StudentModel StuData , FormCollection FormData)
        {
            try
            {
                string data = FormData["Department"];
                StuData.Department = data;
                StudentObj.AddStudent(StuData);
                return RedirectToAction("Index", "Home");
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        public ActionResult GetStudentTable()
        {
            try
            {
                
                return View (GetStudentByIndex(1));
            }
            catch(Exception E)
            {
                throw E;
            }
        }
      
        public ActionResult After(int id)
        {
            try
            {
                return View(GetStudentByIndex(id));
            }
            catch (Exception E)
            {
                throw E;
            }
        }

        public ActionResult Delete(int Id)
        {
            try
            {
                StudentObj.DeleteStudent(Id);
                return RedirectToAction("GetStudentTable");
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                return View(StudentObj.GetDataInEdit(Id));
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]
        public ActionResult Edit(StudentModel Data)
        {
            try
            {
                StudentObj.EditStudent(Data);
                return RedirectToAction("GetStudentTable");
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        public List<Sp_GetStudents_Result> GetStudentByIndex(int id)
        {
            int maxRacord = 5;
            TempData["Record"] = Math.Ceiling((decimal)StudentObj.Studenttable().Count() / maxRacord);
            return StudentObj.Studenttable().OrderBy(x => x.Id).Skip((id - 1) * maxRacord).Take(maxRacord).ToList();
        }
    }
}

PracProject/Controllers/TeacherController.cs
using PracProject.Filter;
using PracProject.Model.Model;
using PracProject.Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracProject.Controllers
{
    [CustomFilter]
    public class TeacherController : Controller
    {
        ITeacher TeacherObj;

        public TeacherController(ITeacher Obj)
        {
            TeacherObj = Obj;
        }
        
        public ActionResult AddTeacher()
        {
            try
            {
            return View();
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]
        public ActionResult Postteacher(TeacherModel Data , FormCollection FormData)
        {
            try
            {
                string Datas = FormData["Subject"];
                Data.Subject = Datas;
                TeacherObj.AddTeaccher(Data);
                return RedirectToAction("AddTeacher");
            }
            catch (Exception E)
            {

                throw E;
            }
        }

        public ActionResult GetTeacher()
        {
            try
            {
                return View(TeacherObj.TeacherTable());
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                return View(TeacherObj.GetData(Id));
            }
            catch(Exception E)
            {
                throw E;
            }
        }

        [HttpPost]
        public ActionResult EditData(TeacherModel TeachData)
        {
            try
            {
                TeacherObj.EditStudent(TeachData);
                return RedirectToAction("GetTeacher");
            }
            catch (Exception E)
            {

                throw E;
            }
        }
    }
}

PracProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href=@Url.Action("AddStudent" , "Student")>AddStudent</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("GetStudentTable" , "Student")>Students</a>
                    </li> <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Quiz" , "Quiz")>Quick Quiz</a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Addteacher" , "Teacher")>Add Teacher</a>
                    </li> <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("GetTeacher" , "Teacher")>Get Teachers</a>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    
                    <button class="btn btn-outline-success" type="submit"><a href=@Url.Action("logout","LoginRegister")>LogOut</a></button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>